<a href="https://colab.research.google.com/github/VKline333/Data_Analysis/blob/main/DS_Pandas_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd
# herşeyden önce numpy i import ediyoruz. Numpy = Numerical Python

In [ ]:
v = np.array([1,1,2,2,3,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3, 3])

In [ ]:
np.mean(v)

# ortalama

2.25

In [ ]:
np.median(v)

# en ortdaki elemandır.

2.5

In [ ]:
np.min(v)

1

In [ ]:
np.var(v)

# variation

0.6875

# a sample solve in Linear Algebra using NumPy

In [ ]:
"""
3x + y = 9
x + 2y = 8
denklemini çözelim
"""

a = np.array([[3,1], [1,2]]) # denklemlerin değişkenlerinik katsayılarını a arrayinde tanımladık.

b = np.array([9,8])  # denklemlerin eşitliklerini b arrayine tanımladık



In [ ]:
a

array([[3, 1],
       [1, 2]])

In [ ]:
b

array([9, 8])

In [ ]:
np.linalg.solve(a,b)

# linalg.solve() fonksiyonu bizi sonuca ulaştıracak

array([2., 3.])

# P a n d a s  ------------   P a n d a s

In [ ]:
# What are the difference and similarities between NumPy arrays and Pandas Series

"""
The Pandas module mainly works with the tabular data, whereas the NumPy module 
works with the numerical data. ... NumPy library provides objects for
multi-dimensional arrays, whereas Pandas is capable of offering 
an in-memory 2d table object called DataFrame.
NumPy consumes less memory as compared to Pandas

The Pandas provides some sets of powerful tools like DataFrame and Series 
that mainly used for analyzing the data, whereas in NumPy module offers 
a powerful object called Array

The essential difference is the presence of the index: while the Numpy Array 
has an implicitly defined integer index used to access the values, 
the Pandas Series has an explicitly defined index associated with the values.

Numpy serilerinde sadece numeric indeksleme yapabiliyorsun ama pandasta istediğin 
indekslemeyi yapabiliyorsun. indeksi indeksleyebiliyorsun

Pandas'ta her bir sütun bir seri oluyor. her seri yan yana gelince bu bir tablo oluyor.
Yani bu bir tablo biçiminde olursa buna DataFrame deniliyor
"""

In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
pd.Series([10, 88, 3, 4, 5])

# pandasta da series oluştururken numpy serilerini kullanabiliriz.

# pandasta datanın gösterimi sütun şeklinde

0    10
1    88
2     3
3     4
4     5
dtype: int64

## Basic Attributes

In [ ]:
ser = pd.Series([10, 88, 3, 4, 5])
ser

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [ ]:
ser.dtype

# serie nin tipi int.

dtype('int64')

In [ ]:
type(ser)

# pandas serisinin tipi pandas serisidir :))

# pandas serisinin içindeki verilerin tipi int.dir.

pandas.core.series.Series

In [ ]:
ser.size

# 5 elemandan oluşuyor

5

In [ ]:
ser.ndim

# 1 dimension

1

In [ ]:
ser.values

array([10, 88,  3,  4,  5], dtype=int64)

In [ ]:
type(ser.values)

# numpy arraylerinin kullandığını görelim.

numpy.ndarray

In [ ]:
for i in ser.values :
    print(i)

10
88
3
4
5


In [ ]:
[i for i in ser.values]

# serinin value larından liste ürettik

[10, 88, 3, 4, 5]

In [ ]:
ser.head(3)

# en tepeden 3 elemanı göster (default değeri 5)

0    10
1    88
2     3
dtype: int64

In [ ]:
ser.tail(2)

# en alltan 2 elemanı göster. (default değeri 5)

3    4
4    5
dtype: int64

In [ ]:
# stringlerden oluşturalım

pd.Series([i for i in "clarusway"]) # listenin içinde clarusway'in karakterlerini soktuk ve bunu serie yaptık 

#  dtype: object yazıyorsa bunun stringlerden oluştuğunu bil. 

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Creating Pandas Series Using a "list", "numpy-array" or "dict"

In [ ]:
labels = ["a", "b", "c"]

my_list = [10, 20, 30]

arr = np.array([10, 20, 30])

d = {"a" : 10, "b" : 20, "c" : 30}

In [ ]:
pd.Series(data = my_list)

# data olarak az önce oluşturduğumuz my_list i kullandık

0    10
1    20
2    30
dtype: int64

In [ ]:
# şimdi index parametresini işin içine katalım

pd.Series(data = my_list, index = labels)

# indeks olarak az önce tanımaldığımız labels değişkenini kullandık
# artık indeksimiz "a","b","c" oldu

a    10
b    20
c    30
dtype: int64

In [ ]:
# değerleri positional argument olarak atayalım. sıralamaya dikkat edeceğiz!

pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

## using numpy arrays

In [ ]:
pd.Series(arr)

# numpy array den seri ürettik

0    10
1    20
2    30
dtype: int32

In [ ]:
pd.Series(arr, labels)

# indeks olarak yine labels değişkenini kullandık. default olan 0,1,2 değişti.

a    10
b    20
c    30
dtype: int32

## using dictionary

In [ ]:
d

# dictionary de keyler indeksleri kastediyor. value lar value oluyor.

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
pd.Series(d)

 # keylerin indeks yerine geçtiğini görelim.

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d, ["w", "c", "z"])

# sözlük kullanmamıza rağmen indeks numaralarını değiştirirsek belirlediğimiz
# değerlerden sadece keyle aynı olan varsa ona değer atıyor.
# diğerlerini yeni value olarak kabul ediyor

# eksik veri yerine NaN ile dolduruyor.

w     NaN
c    30.0
z     NaN
dtype: float64

In [ ]:
a = np.nan

a

nan

# Data in Series

In [ ]:
labels

['a', 'b', 'c']

In [ ]:
pd.Series(data = labels)

# labels ı data olarak belirleyince indeks default değerlere döndü.

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series([sum, print, len])

# fonksiyonları data olarak kullandık

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
mix_data = [1, "cat", True]

# farklı veri tipleri olduğu için dtype object oldu!

In [ ]:
pd.Series(mix_data)

0       1
1     cat
2    True
dtype: object

In [ ]:
pd.Series([True, False, False, True])

0     True
1    False
2    False
3     True
dtype: bool

In [ ]:
# Sorting Index | Sorting Values | Check 

In [ ]:
s = pd.Series(['p', 'q', 'r', 's'], index=[3, 2, 4, 5])
s

3    p
2    q
4    r
5    s
dtype: object

In [ ]:
s.sort_index()

# indekse göre sıraladı

2    q
3    p
4    r
5    s
dtype: object

### inplace = True kullanırsan değişiklik kalıcı olur.

In [ ]:
s.sort_index(inplace = True) 

# inplace = True kullanırsan değişiklik kalıcı olur.
s

2    q
3    p
4    r
5    s
dtype: object

In [ ]:
s = pd.Series(['p', 'q', 'r', 's'], index=[3, 2, 4, np.nan])

# boş kalan index numarası yerine nan kullandık.

In [ ]:
s.sort_index(na_position='first')

 # nan olan indeksi başa almak için position parametresini bu şekilde first'e eşitliyoruz

NaN    s
2.0    q
3.0    p
4.0    r
dtype: object

In [ ]:
s = pd.Series(['p', 'q', 'r', 's'], index=[3, 2, 4, 5])
s.sort_index()

2    q
3    p
4    r
5    s
dtype: object

In [ ]:
s.sort_index(ascending=False)

5    s
4    r
3    p
2    q
dtype: object

In [ ]:
s.sort_index(inplace=True)
s

2    q
3    p
4    r
5    s
dtype: object

In [ ]:
s = pd.Series(['dog', 'cow', 'dog', 'cat', 'dog',
               'lion'], name='animal')

In [ ]:
s

0     dog
1     cow
2     dog
3     cat
4     dog
5    lion
Name: animal, dtype: object

In [ ]:
s.isin(['cow', 'dog'])

# cow ve dog hangi satırda ise o satırı True olarak görüyoruz.
# sorguladığımız datanın hangi indekste (hangi satırda) olduğunu böylece görebiliriz
# sonra da o dataya ulaşabiliriz

0     True
1     True
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

In [ ]:
s.isin(['dog'])

0     True
1    False
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

In [ ]:
 ## Indexinbg

In [ ]:
# indeks 2 şekilde belirlenir
# indeks numarası default olarak 0 dan başlar ve gider
# ya da indeksin kendisini kullanabilirsin

In [ ]:
ser1 = pd.Series([1,2,3,4], index = ['USA', "Germany", "USSR", "Japan"])

ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [ ]:
ser2 = pd.Series([1,2,3,4], index = ['USA', "Germany", "Italy", "Japan"])

In [ ]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [ ]:
ser1["USA"]

# görüldüğü gibi listelerde olduğu gibi indeksleme yabilirim

1

In [ ]:
ser1[0]

# arka planda hafızasında tuttuğu default index numaralarını da kullanıp indeksleme yapabilirsin

1

In [ ]:
labels = ['a', 'b', 'c']

In [ ]:
ser3  =pd.Series(data = labels)
ser3

0    a
1    b
2    c
dtype: object

In [ ]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [ ]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [ ]:
ser1 + ser2

# Italy ser1 de, SSCB ser2 de olmadığı için onların olduğu satırı toplayamadığı için yerine NaN koydu.

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [ ]:
a = np.array([1,2,33,444,75])

In [ ]:
panser = pd.Series(a)
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [ ]:
panser[0]

1

In [ ]:
panser[1:3]

1     2
2    33
dtype: int32

In [ ]:
panser = pd.Series([121, 200, 150, 99], index = ["ali", "veli", "ayşe", "nur"])

In [ ]:
panser

ali     121
veli    200
ayşe    150
nur      99
dtype: int64

In [ ]:
panser[0]

121

In [ ]:
panser[["veli", "nur"]]

veli    200
nur      99
dtype: int64

In [ ]:
panser["veli" : "nur"]

 # fancy nin köşeli parantezini kaldırıp araya : koyarsak 
# veli den başlayıp nur'a kadar gider. Nur dahil !!!

veli    200
ayşe    150
nur      99
dtype: int64

In [ ]:
panser[0:3]

# burada 3. indeksi almadı. ama yukardaki örnekte Nur'u aldı.
# serinin indekslerinin İSİMLERİ ile indeksleme yaparsan SON İNDEKSİ DE ALIR!!

ali     121
veli    200
ayşe    150
dtype: int64

## Several Selecting Attributes

In [ ]:
panser.index

# index object oluşturdu. indeksleri verdi.

Index(['ali', 'veli', 'ayşe', 'nur'], dtype='object')

In [ ]:
panser.keys

<bound method Series.keys of ali     121
veli    200
ayşe    150
nur      99
dtype: int64>

In [ ]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [ ]:
panser.items

<bound method Series.items of ali     121
veli    200
ayşe    150
nur      99
dtype: int64>

In [ ]:
panser.items()

In [ ]:
# list fonksiyonu kullanarak liste görünümünde görelim.

list(panser.items())

[('ali', 121), ('veli', 200), ('ayşe', 150), ('nur', 99)]

In [ ]:
# for döngüsü ile görelim.

for index, value in panser.items() :
    print(index, "-", value)

ali - 121
veli - 200
ayşe - 150
nur - 99


In [ ]:
"mehmet" in panser

# in OPERATÖRÜ İNDEKSLERE BAKTIĞI İÇİN mehmet indeksi olmadığından false verdi.

False

In [ ]:
121 in panser

# 121 diye bir indeks olmadığından false verdi.

False

In [ ]:
121. in panser.values

# value ler içinde baktığımız için 121 valueler arasında olduğundan true verdi.

True

In [ ]:
500 in panser.values

False

In [ ]:
panser["veli"] = 571
panser
# = ile veli nin değerini değiştirebiliyoruz. 

ali     121
veli    571
ayşe    150
nur      99
dtype: int64

In [ ]:
# conditional indexing yapalım

panser > 130

# bize AYNI UZUNLUKTA BİR SERİ döndürdü. conditionu sağlayanları True yaptı.

ali     False
veli     True
ayşe     True
nur     False
dtype: bool

In [ ]:
panser[panser > 130]

# panser > 130 u sağlayan value'ların indeksini çektik

veli    571
ayşe    150
dtype: int64

In [ ]:
panser[[False, True, True, False]]

# manipule edip elle booleanlarını yazınca da aynı sonucu elde ettim

veli    571
ayşe    150
dtype: int64

# DataFrames

In [ ]:
"""
serilerin sütun olarak bir araya geldiği, 
ve aynı indeksleri paylaştığı verilerdir.
"""

## Creating DataFrame using list

In [ ]:
datam = [1, 2, 39, 67, 90]

In [ ]:
datam

[1, 2, 39, 67, 90]

In [ ]:
# DataFrame, parametre olarak iterables alır.

pd.DataFrame(datam, columns = ["column_name"])

# DataFrame'e column_name ismi verdik. Series'de de isim verebiliyoruz. (buna daha sonra bak)

column_name
0            1
1            2
2           39
3           67
4           90

In [ ]:
m = np.arange(1, 10).reshape(3, 3)

In [ ]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
pd.DataFrame(m, columns = ["var1", "var2", "var3"])

# her bir "var sütunu"nun birer pandas serie olduğuna dikkat et

# "columns =" yazmadan doğrudan varları yazamam. 
# çünkü parametrelere baktığımızda arada index parametresi var!
# positioning olayı...

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
pd.DataFrame(data = m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
df = pd.DataFrame(data = m, columns = ["var1", "var2", "var3"])

In [ ]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [ ]:
df.tail(1)

var1  var2  var3
2     7     8     9

In [ ]:
df.columns

# columnsları görelim.

Index(['var1', 'var2', 'var3'], dtype='object')

In [ ]:
df.columns = ["new1", "new2", "new3"]
df

# columns ların isimlerine yeni atama yaparak onları değiştirdik.

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.shape

(3, 3)

In [ ]:
df.size

9

In [ ]:
df.values

# dataframe'imizin içerisindeki numpy karşılığını verdi. array olduğunu gördük

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating a DataFrame using a dict

In [ ]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [ ]:
s1

array([1, 8, 3, 1, 2])

In [ ]:
s2

array([1, 6, 0, 5, 7])

In [ ]:
s3

array([4, 0, 4, 4, 6])

In [ ]:
mydict = {"var1" : s1, "var2" : s2, "var3" : s3}

In [ ]:
mydict

{'var1': array([1, 8, 3, 1, 2]),
 'var2': array([1, 6, 0, 5, 7]),
 'var3': array([4, 0, 4, 4, 6])}

In [ ]:
# şimdi bunu dataframe e dönüştüreceğiz. 
# her bir key column name olacak

df1 = pd.DataFrame(mydict)

In [ ]:
df1

var1  var2  var3
0     1     1     4
1     8     6     0
2     3     0     4
3     1     5     4
4     2     7     6

In [ ]:
pd.read_csv("ornekcsv.csv", delimiter = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [ ]:
df1[1:3]

# satır bazında indeksledik. (1 ve 2.satırları aldık 3 ü almadık.)

# dataframe i slicing yaptık.

var1  var2  var3
1     8     6     0
2     3     0     4

In [ ]:
df[1]

# böyle YAPAMIYORUZ! ama yukardaki gibi slice lama yapabiliyoruz.

KeyError: 1

In [ ]:
pwd

'C:\\Users\\hüseyin'

In [ ]:
df1

var1  var2  var3
0     1     1     4
1     8     6     0
2     3     0     4
3     1     5     4
4     2     7     6

In [ ]:
[i for i in df1.index]

# indekslerimizi görelim.

[0, 1, 2, 3, 4]

In [ ]:
df1.index = ["a", "b", "c", "d", "e"]

# indeks isimlerini değiştirdik

In [ ]:
df1

var1  var2  var3
a     1     1     4
b     8     6     0
c     3     0     4
d     1     5     4
e     2     7     6

In [ ]:
df1["b" : "d"]

# indeks isimleri üzerinden slice lama yaptık. d dahil gösterdi.

var1  var2  var3
b     8     6     0
c     3     0     4
d     1     5     4

In [ ]:
"var2" in df1

# in operatörü COLUMN lar üzerinde çalışıyor.

True

In [ ]:
9 in df1

# 9 diye bir column olmadığı için false verdi.

False